server.port: 8080

# Actuator
management.port: 8081

issues-location: "/opt/speakunited-api/issues.json"
google-api-key-location: "/opt/speakunited-api/google-api-key.yml"
phaxio-api-key-location: "/opt/speakunited-api/phaxio-api-dev.yml"
lob-api-key-location: "/opt/speakunited-api/lob-api-dev.yml"
stripe-api-key-location: ""